 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/controller_name", type: :request do
  # ControllerName. As you add validations to ControllerName, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ControllerName.create! valid_attributes
      get controller_name_index_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      controller_name = ControllerName.create! valid_attributes
      get controller_name_url(controller_name)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_controller_name_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      controller_name = ControllerName.create! valid_attributes
      get edit_controller_name_url(controller_name)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ControllerName" do
        expect {
          post controller_name_index_url, params: { controller_name: valid_attributes }
        }.to change(ControllerName, :count).by(1)
      end

      it "redirects to the created controller_name" do
        post controller_name_index_url, params: { controller_name: valid_attributes }
        expect(response).to redirect_to(controller_name_url(ControllerName.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ControllerName" do
        expect {
          post controller_name_index_url, params: { controller_name: invalid_attributes }
        }.to change(ControllerName, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post controller_name_index_url, params: { controller_name: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested controller_name" do
        controller_name = ControllerName.create! valid_attributes
        patch controller_name_url(controller_name), params: { controller_name: new_attributes }
        controller_name.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the controller_name" do
        controller_name = ControllerName.create! valid_attributes
        patch controller_name_url(controller_name), params: { controller_name: new_attributes }
        controller_name.reload
        expect(response).to redirect_to(controller_name_url(controller_name))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        controller_name = ControllerName.create! valid_attributes
        patch controller_name_url(controller_name), params: { controller_name: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested controller_name" do
      controller_name = ControllerName.create! valid_attributes
      expect {
        delete controller_name_url(controller_name)
      }.to change(ControllerName, :count).by(-1)
    end

    it "redirects to the controller_name list" do
      controller_name = ControllerName.create! valid_attributes
      delete controller_name_url(controller_name)
      expect(response).to redirect_to(controller_name_index_url)
    end
  end
end
